version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.10
  - dependency-name: "@salesforce/design-system-react"
    versions:
    - 0.10.27
    - 0.10.29
    - 0.10.30
  - dependency-name: use-debounce
    versions:
    - 5.2.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
