version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build-and-test:
    executor:
      name: 'node/default'
      tag: '16.13.1'
    steps:
      - checkout
      - restore_cache:
         keys:
           - v2-deps-{{ checksum "yarn.lock" }}
           - v2-deps-{{ checksum "package.json" }}
           - v2-deps-
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: v2-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - save_cache:
          key: v2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
    build-and-test:
      jobs:
        - build-and-test
