export const CHANGE_FORMULA = 'CHANGE_FORMULA'
export const CHANGE_IDENTIFIER = 'CHANGE_IDENTIFIER'
export const CHANGE_IDENTIFIER_VALUE = 'CHANGE_IDENTIFIER_VALUE'
export const CHANGE_IDENTIFIER_DATA_TYPE = 'CHANGE_IDENTIFIER_DATA_TYPE'
